default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
      username: DijkstraBot

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
